version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=main_db
    healthcheck:
      test: pg_isready -U root -d main_db
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    image: api:latest
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/main_db?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

networks:
  default:
    name: ww-network
